plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    
    id("com.android.application")
    id("kotlin-android")
    id("org.jetbrains.kotlin.plugin.compose")
    
}

android {
    namespace = "com.github.compose"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.github.compose"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.10.0")
    implementation("androidx.activity:activity-compose:1.12.2")
    implementation(platform("androidx.compose:compose-bom:2025.10.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.appcompat:appcompat:1.7.1")
    implementation("androidx.compose.foundation:foundation")
   // implementation("androidx.compose.material:material")
    implementation("androidx.compose.material:material-icons-extended")
   // debugImplementation("androidx.compose.ui:ui-tooling")
   // debugImplementation("androidx.compose.ui:ui-test-manifest")
   // androidTestImplementation ("androidx.compose.ui:ui-test-junit4:1.11.0-alpha02") // Check for the latest version
   // androidTestImplementation ("androidx.test.espresso:espresso-core:3.7.0") // For activities and intents if needed
}
